name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "🎉 Congratulations on opening the first Issue for @teteu/utils! 🎉"
        pr-message: "🎉 Congratulations on submitting the first Pull Request for @teteu/utils! 🎉"
